### PR TITLE
Use onSend hook rather than preSeriailization

### LINKED ISSUE #1: Support for binary responses
Hi, thanks for writing this and the [associated work here](https://github.com/fastify/fastify/pull/4537). I first tried to use your plugin and found that it wasn't supporting binary responses (pdf file for example) but looking at your plugin I discovered the trick I've been searching for which is the `Readable.fromWeb` method. So all in all, I'm not using your plugin, but instead converting the ReadableStream (response body) which Fastify is happy to stream. Here's one of your examples modified for my solution:

```javascript
import { Readable } from 'node:stream'

app.route({
  method: "GET",
  url: "/",
  async handler() {
    const { body } = await fetch("https://example-api.com")
    return Readable.fromWeb(body)
  }
})
```

### PR DESCRIPTION
**Pull request by curiousercreative**
Fixes https://github.com/erfanium/fastify-web-response/issues/1

### CODE REVIEW

**Comment by erfanium** [comment]
Sorry but tests are not passing. run `npm run test`

image

**Comment by curiousercreative** [comment]
@erfanium sorry about that, should be passing now.

**Comment by erfanium** [comment]
nice,Thank you!

**Comment by curiousercreative** [comment]
@erfanium thanks for the quick feedback and merge. Do you plan to publish a release? I'd love to leverage the package now that it supports my use case.

**Comment by erfanium** [comment]
@curiousercreative yeah
I'll do it in 24h

**Comment by erfanium** [comment]
@curiousercreative sorry for being late
released in fastify-web-response@0.1.2

**Pull request merged**
